name: mobile_chat_ui
description: A fully customizable modern chat UI for Android, IOS and web developers.
version: 1.0.0
homepage: https://github.com/ayzerobug/mobile_chat_ui

environment:
    sdk: ">=2.17.6 <4.0.0"
    flutter: ">=1.17.0"

dependencies:
    audio_wave: ^0.1.5
    cached_network_image: ^3.4.1
    flutter:
        sdk: flutter
    flutter_linkify: ^6.0.0
    iconify_flutter: ^0.0.7
    url_launcher: ^6.3.1
    image_picker: ^1.1.2
    emoji_picker_flutter: ^4.3.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^5.0.0
    lints: ^5.1.1
